# Generated by Django 6.0.3 on 2026-04-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0002_about_contact_faq_home_statistic_testimonial_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
