# Generated by Django 6.0.3 on 2026-04-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medinest', '0003_delete_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default=1, upload_to='services/', verbose_name='photo'),
            preserve_default=False,
        ),
    ]
