# Generated by Django 6.0.3 on 2026-03-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200, verbose_name='title')),
                ('title2', models.CharField(max_length=200, verbose_name='title')),
                ('text1', models.TextField(verbose_name='text1')),
                ('text2', models.TextField(verbose_name='text2')),
                ('text3', models.TextField(verbose_name='text3')),
                ('img1', models.ImageField(upload_to='home', verbose_name='img')),
                ('img2', models.ImageField(upload_to='home', verbose_name='img')),
                ('img3', models.ImageField(upload_to='home', verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=200, verbose_name='title')),
                ('text', models.TextField(help_text='text', verbose_name='desciption')),
                ('img', models.ImageField(upload_to='home')),
            ],
        ),
    ]
